import { Imagesdata } from "./commonimages";

export const ItemData =
[
    {
      id:1,
      PREVIEW: Imagesdata('pngs9'),
      TITLE: "Bracelets",
      PRICE: "$16,599",
      PRICES: "$19,799",
      IMG:[
        { "img":Imagesdata("pngs9")},
        { "img":Imagesdata("pngs91")},
        { "img":Imagesdata("pngs92")},
    ],
      STATUS: "stock ",
      bgColor: "success",
    },
    {
      id:2,
      PREVIEW: Imagesdata('pngs1'),
      TITLE: "Cup",
      PRICE: "$529",
      PRICES: "$799",
      IMG:[
        { "img":Imagesdata("pngs1")},
        { "img":Imagesdata("pngs11")},
        { "img":Imagesdata("pngs12")},
    ],
      STATUS: "instock",
      bgColor: "danger",
    },
    {
      id:3,
      PREVIEW: Imagesdata('pngs7'),
      TITLE: "Stool",
      PRICE: "$25,239",
      PRICES: "$34,399",
      IMG:[
        { "img":Imagesdata("pngs7")},
        { "img":Imagesdata("pngs71")},
        { "img":Imagesdata("pngs72")},
    ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id:4,
      PREVIEW: Imagesdata('pngs2'),
      TITLE: "Video Game",
      PRICE: "$345",
      PRICES: "$459",
      IMG:[
        { "img":Imagesdata("pngs2")},
        { "img":Imagesdata("pngs21")},
        { "img":Imagesdata("pngs22")},
    ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id:5,
      PREVIEW: Imagesdata('pngs4'),
      TITLE: "Flower Pot",
      PRICE: "$277",
      PRICES: "$456",
      IMG:[
        { "img":Imagesdata("pngs4")},
        { "img":Imagesdata("pngs41")},
        { "img":Imagesdata("pngs42")},
    ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id:6,
      PREVIEW: Imagesdata('pngs8'),
      TITLE: "Watch",
      PRICE: "$567",
      PRICES: "$866",
      IMG:[
        { "img":Imagesdata("pngs8")},
        { "img":Imagesdata("pngs81")},
        { "img":Imagesdata("pngs82")},
    ],
      STATUS: "instock",
      bgColor: "danger",
    },
    {
      id:7,
      PREVIEW: Imagesdata('pngs3'),
      TITLE: "Headset",
      PRICE: "$455",
      PRICES: "$567",
      IMG:[
        { "img":Imagesdata("pngs3")},
        { "img":Imagesdata("pngs33")},
        { "img":Imagesdata("pngs32")},
    ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id:8,
      PREVIEW: Imagesdata('pngs5'),
      TITLE: "Chair",
      PRICE: "$345",
      PRICES: "$499",
      IMG:[
        { "img":Imagesdata("pngs5")},
        { "img":Imagesdata("pngs51")},
        { "img":Imagesdata("pngs52")},
    ],
      STATUS: "stock",
      bgColor: "success",
    },
    {
      id:9,
      PREVIEW: Imagesdata('pngs6'),
      TITLE: "Goggles",
      PRICE: "$543",
      PRICES: "$688",
      IMG:[
        { "img":Imagesdata("pngs6")},
        { "img":Imagesdata("pngs61")},
        { "img":Imagesdata("pngs62")},
    ],
      STATUS: "stock",
      bgColor: "success",
    },
  ];
  